var toDo = [
"☐ See a Broadway show",
"☐ Run a lap on the rooftop track of Coles",
"☐ Read the Washington Square News",
"☐ Take a nap in the Kimmel Center",
"☐ Take a walk through Central Park",
"☐ Hug John Sexton",
"☐ Drink Coffee at Starbucks on the Square",
"☐ Go to a Commuter Luncheon on a Tuesday",
"☐ Buy movie and concert tickets at Ticket Central",
"☐ Walk through a movie shoot on the street",
"☐ Kiss the Bobcat",
"☐ Ride the NYU Trolley",
"☐ Take a course at Coles or Palladium",
"☐ Read a book in Washington Square Park",
"☐ Meet 'Albert'",
"☐ Attend a student performance",
"☐ Work an unpaid internship",
"☐ Visit the Wasserman Center for Career Development",
"☐ Learn the name of an NYU Public Safely Officer",
"☐ Set-up and use your NYU email",
"☐ Join at least one listserve",
"☐ Obtain an article of clothing that has 'NYU' on it",
"☐ Participate in a Community Service project",
"☐ Meet your Student Senator Rep",
"☐ Learn to do your laundry",
"☐ Meet at least one undergraduate in each NYU school",
"☐ Participate or cheer in NYU 'Tear It Up!' events",
"☐ Attend Violet Ball",
"☐ Eat shortcake at the Strawberry Fest",
"☐ Participate in AIDS Walk NYC",
"☐ Attend a career fair",
"☐ Buy a book from a street book vendor",
"☐ Spend time with a professor outside of class",
"☐ Take a Speaking Freely class",
"☐ Ride the Staten Island Ferry",
"☐ Go to a museum on free days",
"☐ Go to President's Welcome and Picnic",
"☐ Use your NYU ID to get NYU and student discounts",
"☐ Explain the Bobcat to non-NYU folk",
"☐ Climb the rock wall at Palladium",
"☐ Go to the top of Bobst Library and look down at the spiky floor",
"☐ Go to an NYC street fair",
"☐ Attend Grad Alley",
"☐ Attend a culture event at Lincoln Center",
"☐ Learn what CMEP stands for",
"☐ Check out a book from the library",
"☐ Talk to a Dean",
"☐ Learn about five famous NYU Alums",
"☐ Use Blackboard",
"☐ See the Reality Show",
"☐ Be a tourist for a day",
"☐ Use the Broke Student's Guide",
"☐ Visit Columbia University",
"☐ Memorize the numbers for Public Safety and the Wellness Exchange",
"☐ Shop on Canal Street",
"☐ Ice skate at Wollman Rink",
"☐ Visit the Union Square Farmer's Market",
"☐ Ride the subway",
"☐ Go to the top of the Empire State Building",
"☐ Find a famous landmark or location from a movie or television show",
"☐ Visit another borough",
"☐ Attend a Sexton Town Hall Meeting or Dinner",
"☐ Attend Welcome Week and Back to the Square events",
"☐ Attend a lecture or performance at Skirball Center",
"☐ Ride the elevators in the Silver Center",
"☐ Learn about the history of NYU",
"☐ Read the Student's Guide",
"☐ Eat falafel from Mamoun's",
"☐ Get a slide of pizza from Pizza Mercado",
"☐ Partake in the fare of Dojo's",
"☐ Help a tourist with directions",
"☐ Go to a Yankee's game",
"☐ See a celebrity",
"☐ Watch an NYC movie and count the number of places you've been to or recognize",
"☐ Proofread a friend's paper",
"☐ Show off the campus and Village to a family member or friend",
"☐ Try a different ethnic cuisine",
"☐ Take advantage of Summer and Winter Restaurant Weeks",
"☐ Go to an NYC parade",
"☐ Visit the Health Center",
"☐ Apply for a scholarship or grant",
"☐ Use your Campus Cash",
"☐ Watch $2 films courtesy of the Program Board's Film Series",
"☐ Watch NYU-TV",
"☐ Listen to NYU-Radio",
"☐ Learn the Alma Matter",
"☐ Vote",
"☐ Study Aboad",
"☐ Take a break from studying at the library and watch a movie in the Avery Fischer Center",
"☐ Take the subway to a neighborhood you've never visited",
"☐ Get out of the city for a weekend",
"☐ Go to a historic walking tour of an NYC neighborhood",
"☐ Play with toys from FAO Shwartz",
"☐ Rent a rowboat in Central Park",
"☐ Picnic in Fort Tryon Park and visit the Cloisters",
"☐ Eat hot dogs from Gray's Papaya",
"☐ Attend the San Gennero Festival in Little Italy",
"☐ Go to a filming of the Daily Show, Conan O'Brian, or Letterman",
"☐ Get your name in the Washington Square News",
"☐ Attend a free concert in Central Park",
"☐ Earn your degree"
];

